name: test run for trivy

on:
  push:
    branches:
      - main

jobs:

  BuildImage-PushToHub-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract Git SHA
        id: vars
        run: echo "GIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        id: docker_build
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/apd:${{ env.GIT_SHA }} .

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install -y trivy

      - name: Scan Docker image with Trivy
        id: trivy_scan
        run: |
          trivy image --severity HIGH,CRITICAL --no-progress ${{ secrets.DOCKER_HUB_USERNAME }}/apd:${{ env.GIT_SHA }} > trivy_report.txt
          cat trivy_report.txt

      - name: Push Docker image to Docker Hub
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/apd:${{ env.GIT_SHA }}

    



      - name: Send Trivy Report to Slack
        if: success()
        run: |
          # Extract summary information from the Trivy report
          vulnerabilities=$(grep -E '^[^ ]+ (HIGH|CRITICAL)' trivy_report.txt | wc -l)
          high_vulns=$(grep 'HIGH' trivy_report.txt | wc -l)
          critical_vulns=$(grep 'CRITICAL' trivy_report.txt | wc -l)
          
          # Create a summary message
          msg="The Trivy scan completed with the following results:\n\n*Total Vulnerabilities: ${vulnerabilities}*\n*High Vulnerabilities: ${high_vulns}*\n*Critical Vulnerabilities: ${critical_vulns}*"
          
          # Send summary to Slack
          payload=$(jq -n --arg msg "$msg" '{text: "*Trivy Scan Report:*\n\n\($msg)"}')
          curl -X POST -H 'Content-type: application/json' --data "$payload" ${{ secrets.SLACK_WEBHOOK_URL_ALERTS }}


      
