name: test run for trivy with encryption txt file

on:
  push:
    branches:
      - main

jobs:
  BuildImage-PushToHub-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract Git SHA
        id: vars
        run: echo "GIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        id: docker_build
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/apd:${{ env.GIT_SHA }} .

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install -y trivy

      - name: Scan Docker image with Trivy
        id: trivy_scan
        run: |
          trivy image --severity HIGH,CRITICAL --no-progress ${{ secrets.DOCKER_HUB_USERNAME }}/apd:${{ env.GIT_SHA }} > trivy_report.txt
          trivy image --severity HIGH,CRITICAL --format json --no-progress ${{ secrets.DOCKER_HUB_USERNAME }}/apd:${{ env.GIT_SHA }} > trivy_report.json

      - name: Send Trivy Report to Slack
        if: success()
        run: |
          # Upload the trivy_report.txt file to Slack using the new files.upload_v2 method
          response=$(curl -F file=@trivy_report.txt \
                      -F "initial_comment=Trivy scan report for commit ${{ env.GIT_SHA }}" \
                      -F channels=C07G5HVC2G4  \
                      -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
                      https://slack.com/api/files.upload_v2)
    
          echo "Slack API response: $response"
