name: Scan, Build Image, Push, and Update Image Name test

on:
  push:
    branches:
      - main

jobs:

  NotifyWorkflowStart:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Start
        run: |
          payload=$(jq -n --arg msg "The \`APD_ADMIN\` merge succesfull, starting git action..." \
          '{text: "*Workflow Notification:*\n\n\($msg)"}')
          curl -X POST -H 'Content-type: application/json' --data "$payload" ${{ secrets.SLACK_WEBHOOK_URL_ALERTS }}

  #######################################################        
  
